-- SAMAK Library Management System
-- Run this file once in Supabase Dashboard > SQL Editor.

begin;

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique check (username ~ '^[a-z0-9._-]{3,50}$'),
  full_name text not null check (char_length(trim(full_name)) between 2 and 120),
  role text not null default 'librarian' check (role in ('admin', 'librarian')),
  active boolean not null default true,
  created_by uuid null references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  last_login_at timestamptz null
);

create table if not exists public.library_settings (
  id smallint primary key default 1 check (id = 1),
  library_name text not null default 'کتابخانه دبیرستان شهید شیر آقائی',
  loan_days_default integer not null default 10 check (loan_days_default between 1 and 365),
  max_books_per_member integer not null default 3 check (max_books_per_member between 1 and 50),
  max_renewals_per_loan integer not null default 2 check (max_renewals_per_loan between 0 and 20),
  renew_days_per_extend integer not null default 7 check (renew_days_per_extend between 1 and 365),
  grades text[] not null default array['دهم','یازدهم','دوازدهم','پایه','یازدهم - دوازدهم','جامع'],
  fields text[] not null default array['تجربی','ریاضی','انسانی','جامع'],
  default_theme text not null default 'light' check (default_theme in ('light','dark')),
  logo_data text null,
  updated_by uuid null references public.profiles(id) on delete set null,
  updated_at timestamptz not null default now()
);

insert into public.library_settings (id) values (1)
on conflict (id) do nothing;

create table if not exists public.members (
  id bigint generated by default as identity primary key,
  membership_code text not null unique check (char_length(trim(membership_code)) between 1 and 30),
  first_name text not null check (char_length(trim(first_name)) between 1 and 80),
  last_name text not null check (char_length(trim(last_name)) between 1 and 100),
  phone text not null check (char_length(trim(phone)) between 3 and 20),
  national_code text null,
  grade text null,
  field text null,
  commitment boolean not null default true,
  photo_data text null check (photo_data is null or photo_data like 'data:image/%'),
  registered_at timestamptz not null default now(),
  created_by uuid not null references public.profiles(id) on delete restrict,
  updated_at timestamptz not null default now()
);

create index if not exists idx_members_name on public.members(last_name, first_name);
create index if not exists idx_members_phone on public.members(phone);
create index if not exists idx_members_national_code on public.members(national_code);

create table if not exists public.books (
  id bigint generated by default as identity primary key,
  reg_number text not null unique check (char_length(trim(reg_number)) between 1 and 30),
  title text not null check (char_length(trim(title)) between 1 and 250),
  abbr text null,
  grade text null,
  field text null,
  total integer not null default 1 check (total between 1 and 100000),
  available integer not null default 1 check (available >= 0 and available <= total),
  created_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_books_title on public.books(title);
create index if not exists idx_books_available on public.books(available);

create table if not exists public.loans (
  id bigint generated by default as identity primary key,
  member_id bigint not null references public.members(id) on update cascade on delete restrict,
  book_id bigint not null references public.books(id) on update cascade on delete restrict,
  issue_at timestamptz not null default now(),
  due_at timestamptz not null,
  returned_at timestamptz null,
  renew_count integer not null default 0 check (renew_count >= 0),
  last_renewed_at timestamptz null,
  created_by uuid not null references public.profiles(id) on delete restrict,
  returned_by uuid null references public.profiles(id) on delete restrict,
  updated_at timestamptz not null default now(),
  check (due_at >= issue_at),
  check (returned_at is null or returned_at >= issue_at)
);

create index if not exists idx_loans_member on public.loans(member_id);
create index if not exists idx_loans_book on public.loans(book_id);
create index if not exists idx_loans_due_active on public.loans(due_at) where returned_at is null;
create unique index if not exists uq_active_member_book
  on public.loans(member_id, book_id)
  where returned_at is null;

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid null references public.profiles(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists idx_audit_created_at on public.audit_logs(created_at desc);
create index if not exists idx_audit_actor on public.audit_logs(actor_id);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_members_updated on public.members;
create trigger trg_members_updated before update on public.members
for each row execute function public.touch_updated_at();

drop trigger if exists trg_books_updated on public.books;
create trigger trg_books_updated before update on public.books
for each row execute function public.touch_updated_at();

drop trigger if exists trg_loans_updated on public.loans;
create trigger trg_loans_updated before update on public.loans
for each row execute function public.touch_updated_at();

create or replace function public.audit_table_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id text;
begin
  if tg_op = 'DELETE' then
    v_id := old.id::text;
  else
    v_id := new.id::text;
  end if;
  insert into public.audit_logs(actor_id, action, entity_type, entity_id, details)
  values (auth.uid(), lower(tg_op), tg_table_name, v_id, jsonb_build_object('table', tg_table_name));
  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;

drop trigger if exists trg_members_audit on public.members;
create trigger trg_members_audit after insert or update or delete on public.members
for each row execute function public.audit_table_change();

drop trigger if exists trg_books_audit on public.books;
create trigger trg_books_audit after insert or update or delete on public.books
for each row execute function public.audit_table_change();

create or replace function public.current_user_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role from public.profiles where id = auth.uid() and active = true;
$$;

create or replace function public.is_active_user()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(select 1 from public.profiles where id = auth.uid() and active = true);
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.current_user_role() = 'admin', false);
$$;

create or replace function public.write_audit(
  p_action text,
  p_entity_type text,
  p_entity_id text default null,
  p_details jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.audit_logs(actor_id, action, entity_type, entity_id, details)
  values (auth.uid(), p_action, p_entity_type, p_entity_id, coalesce(p_details, '{}'::jsonb));
end;
$$;

alter table public.profiles enable row level security;
alter table public.library_settings enable row level security;
alter table public.members enable row level security;
alter table public.books enable row level security;
alter table public.loans enable row level security;
alter table public.audit_logs enable row level security;

drop policy if exists "profiles_select_self_or_admin" on public.profiles;
drop policy if exists "profiles_admin_update" on public.profiles;
drop policy if exists "settings_active_select" on public.library_settings;
drop policy if exists "settings_admin_update" on public.library_settings;
drop policy if exists "members_active_select" on public.members;
drop policy if exists "members_active_insert" on public.members;
drop policy if exists "members_active_update" on public.members;
drop policy if exists "members_active_delete" on public.members;
drop policy if exists "books_active_select" on public.books;
drop policy if exists "books_active_insert" on public.books;
drop policy if exists "books_active_update" on public.books;
drop policy if exists "books_active_delete" on public.books;
drop policy if exists "loans_active_select" on public.loans;
drop policy if exists "audit_admin_select" on public.audit_logs;

-- Profiles
create policy "profiles_select_self_or_admin" on public.profiles
for select to authenticated
using (id = auth.uid() or public.is_admin());

create policy "profiles_admin_update" on public.profiles
for update to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Settings
create policy "settings_active_select" on public.library_settings
for select to authenticated
using (public.is_active_user());

create policy "settings_admin_update" on public.library_settings
for update to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Members
create policy "members_active_select" on public.members
for select to authenticated using (public.is_active_user());
create policy "members_active_insert" on public.members
for insert to authenticated with check (public.is_active_user() and created_by = auth.uid());
create policy "members_active_update" on public.members
for update to authenticated using (public.is_active_user()) with check (public.is_active_user());
create policy "members_active_delete" on public.members
for delete to authenticated using (public.is_admin());

-- Books
create policy "books_active_select" on public.books
for select to authenticated using (public.is_active_user());
create policy "books_active_insert" on public.books
for insert to authenticated with check (public.is_active_user() and created_by = auth.uid());
create policy "books_active_update" on public.books
for update to authenticated using (public.is_active_user()) with check (public.is_active_user());
create policy "books_active_delete" on public.books
for delete to authenticated using (public.is_admin());

-- Loans are read directly, but write operations must use transactional RPC functions below.
create policy "loans_active_select" on public.loans
for select to authenticated using (public.is_active_user());

-- Audit log is visible only to admins. Inserts are performed by security-definer functions.
create policy "audit_admin_select" on public.audit_logs
for select to authenticated using (public.is_admin());

create or replace function public.mark_login()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'نشست معتبر نیست'; end if;
  update public.profiles set last_login_at = now() where id = auth.uid() and active = true;
end;
$$;

create or replace function public.issue_loan(p_member_id bigint, p_book_id bigint)
returns public.loans
language plpgsql
security definer
set search_path = public
as $$
declare
  v_settings public.library_settings%rowtype;
  v_book public.books%rowtype;
  v_active_count integer;
  v_loan public.loans%rowtype;
begin
  if not public.is_active_user() then raise exception 'دسترسی کاربر معتبر نیست'; end if;

  select * into v_settings from public.library_settings where id = 1;
  perform 1 from public.members where id = p_member_id;
  if not found then raise exception 'عضو یافت نشد'; end if;

  select * into v_book from public.books where id = p_book_id for update;
  if not found then raise exception 'کتاب یافت نشد'; end if;
  if v_book.available <= 0 then raise exception 'این کتاب موجود نیست'; end if;

  select count(*) into v_active_count
  from public.loans
  where member_id = p_member_id and returned_at is null;

  if v_active_count >= v_settings.max_books_per_member then
    raise exception 'حداکثر تعداد امانت این عضو تکمیل شده است';
  end if;

  if exists(select 1 from public.loans where member_id = p_member_id and book_id = p_book_id and returned_at is null) then
    raise exception 'این عضو همین کتاب را در امانت فعال دارد';
  end if;

  insert into public.loans(member_id, book_id, issue_at, due_at, created_by)
  values (p_member_id, p_book_id, now(), now() + make_interval(days => v_settings.loan_days_default), auth.uid())
  returning * into v_loan;

  update public.books set available = available - 1 where id = p_book_id;
  perform public.write_audit('issue', 'loan', v_loan.id::text, jsonb_build_object('member_id', p_member_id, 'book_id', p_book_id));
  return v_loan;
end;
$$;

create or replace function public.return_loan(p_loan_id bigint)
returns public.loans
language plpgsql
security definer
set search_path = public
as $$
declare
  v_loan public.loans%rowtype;
begin
  if not public.is_active_user() then raise exception 'دسترسی کاربر معتبر نیست'; end if;
  select * into v_loan from public.loans where id = p_loan_id for update;
  if not found then raise exception 'امانت یافت نشد'; end if;
  if v_loan.returned_at is not null then return v_loan; end if;

  update public.loans
  set returned_at = now(), returned_by = auth.uid()
  where id = p_loan_id
  returning * into v_loan;

  update public.books set available = least(total, available + 1) where id = v_loan.book_id;
  perform public.write_audit('return', 'loan', p_loan_id::text, jsonb_build_object('book_id', v_loan.book_id));
  return v_loan;
end;
$$;

create or replace function public.renew_loan(p_loan_id bigint)
returns public.loans
language plpgsql
security definer
set search_path = public
as $$
declare
  v_loan public.loans%rowtype;
  v_settings public.library_settings%rowtype;
begin
  if not public.is_active_user() then raise exception 'دسترسی کاربر معتبر نیست'; end if;
  select * into v_settings from public.library_settings where id = 1;
  select * into v_loan from public.loans where id = p_loan_id for update;
  if not found then raise exception 'امانت یافت نشد'; end if;
  if v_loan.returned_at is not null then raise exception 'امانت بازگشت داده شده است'; end if;
  if v_loan.renew_count >= v_settings.max_renewals_per_loan then raise exception 'حداکثر دفعات تمدید تکمیل شده است'; end if;

  update public.loans
  set due_at = greatest(due_at, now()) + make_interval(days => v_settings.renew_days_per_extend),
      renew_count = renew_count + 1,
      last_renewed_at = now()
  where id = p_loan_id
  returning * into v_loan;

  perform public.write_audit('renew', 'loan', p_loan_id::text, jsonb_build_object('renew_count', v_loan.renew_count, 'due_at', v_loan.due_at));
  return v_loan;
end;
$$;

create or replace function public.delete_loan(p_loan_id bigint)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_loan public.loans%rowtype;
begin
  if not public.is_active_user() then raise exception 'دسترسی کاربر معتبر نیست'; end if;
  select * into v_loan from public.loans where id = p_loan_id for update;
  if not found then raise exception 'امانت یافت نشد'; end if;

  if v_loan.returned_at is null then
    update public.books set available = least(total, available + 1) where id = v_loan.book_id;
  end if;
  delete from public.loans where id = p_loan_id;
  perform public.write_audit('delete', 'loan', p_loan_id::text, jsonb_build_object('member_id', v_loan.member_id, 'book_id', v_loan.book_id));
  return true;
end;
$$;

create or replace function public.update_book_inventory(p_book_id bigint, p_payload jsonb)
returns public.books
language plpgsql
security definer
set search_path = public
as $$
declare
  v_book public.books%rowtype;
  v_new_total integer;
  v_borrowed integer;
begin
  if not public.is_active_user() then raise exception 'دسترسی کاربر معتبر نیست'; end if;
  select * into v_book from public.books where id = p_book_id for update;
  if not found then raise exception 'کتاب یافت نشد'; end if;

  v_new_total := (p_payload->>'total')::integer;
  if v_new_total < 1 or v_new_total > 100000 then raise exception 'تعداد کل نامعتبر است'; end if;
  v_borrowed := v_book.total - v_book.available;
  if v_new_total < v_borrowed then
    raise exception 'تعداد کل نمی‌تواند از تعداد نسخه‌های در امانت کمتر باشد';
  end if;

  update public.books set
    reg_number = trim(p_payload->>'reg_number'),
    title = trim(p_payload->>'title'),
    abbr = nullif(trim(p_payload->>'abbr'), ''),
    grade = nullif(trim(p_payload->>'grade'), ''),
    field = nullif(trim(p_payload->>'field'), ''),
    total = v_new_total,
    available = v_new_total - v_borrowed
  where id = p_book_id
  returning * into v_book;

  perform public.write_audit('update', 'book', p_book_id::text, jsonb_build_object('total', v_new_total, 'available', v_book.available));
  return v_book;
end;
$$;

create or replace function public.restore_backup(p_backup jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_item jsonb;
  v_settings jsonb;
  v_members_count integer := 0;
  v_books_count integer := 0;
  v_loans_count integer := 0;
begin
  if not public.is_admin() then raise exception 'فقط مدیر سامانه اجازه بازیابی دارد'; end if;
  if coalesce((p_backup->>'version')::integer, 0) <> 2 then raise exception 'نسخه پشتیبان معتبر نیست'; end if;
  if jsonb_typeof(p_backup->'members') <> 'array' or jsonb_typeof(p_backup->'books') <> 'array' or jsonb_typeof(p_backup->'loans') <> 'array' then
    raise exception 'ساختار پشتیبان معتبر نیست';
  end if;

  delete from public.loans;
  delete from public.members;
  delete from public.books;

  for v_item in select value from jsonb_array_elements(p_backup->'members') loop
    insert into public.members(id, membership_code, first_name, last_name, phone, national_code, grade, field, commitment, photo_data, registered_at, created_by, updated_at)
    values (
      (v_item->>'id')::bigint, trim(v_item->>'membership_code'), trim(v_item->>'first_name'), trim(v_item->>'last_name'),
      trim(v_item->>'phone'), nullif(v_item->>'national_code',''), nullif(v_item->>'grade',''), nullif(v_item->>'field',''),
      coalesce((v_item->>'commitment')::boolean, true), nullif(v_item->>'photo_data',''),
      coalesce((v_item->>'registered_at')::timestamptz, now()), auth.uid(), now()
    );
    v_members_count := v_members_count + 1;
  end loop;

  for v_item in select value from jsonb_array_elements(p_backup->'books') loop
    insert into public.books(id, reg_number, title, abbr, grade, field, total, available, created_by, created_at, updated_at)
    values (
      (v_item->>'id')::bigint, trim(v_item->>'reg_number'), trim(v_item->>'title'), nullif(v_item->>'abbr',''),
      nullif(v_item->>'grade',''), nullif(v_item->>'field',''), greatest(1,(v_item->>'total')::integer),
      greatest(0, least((v_item->>'total')::integer, (v_item->>'available')::integer)), auth.uid(),
      coalesce((v_item->>'created_at')::timestamptz, now()), now()
    );
    v_books_count := v_books_count + 1;
  end loop;

  for v_item in select value from jsonb_array_elements(p_backup->'loans') loop
    insert into public.loans(id, member_id, book_id, issue_at, due_at, returned_at, renew_count, last_renewed_at, created_by, returned_by, updated_at)
    values (
      (v_item->>'id')::bigint, (v_item->>'member_id')::bigint, (v_item->>'book_id')::bigint,
      (v_item->>'issue_at')::timestamptz, (v_item->>'due_at')::timestamptz,
      nullif(v_item->>'returned_at','')::timestamptz, coalesce((v_item->>'renew_count')::integer,0),
      nullif(v_item->>'last_renewed_at','')::timestamptz, auth.uid(),
      case when nullif(v_item->>'returned_at','') is null then null else auth.uid() end, now()
    );
    v_loans_count := v_loans_count + 1;
  end loop;

  v_settings := p_backup->'library_settings';
  if jsonb_typeof(v_settings) = 'object' then
    update public.library_settings set
      library_name = coalesce(nullif(v_settings->>'library_name',''), library_name),
      loan_days_default = coalesce((v_settings->>'loan_days_default')::integer, loan_days_default),
      max_books_per_member = coalesce((v_settings->>'max_books_per_member')::integer, max_books_per_member),
      max_renewals_per_loan = coalesce((v_settings->>'max_renewals_per_loan')::integer, max_renewals_per_loan),
      renew_days_per_extend = coalesce((v_settings->>'renew_days_per_extend')::integer, renew_days_per_extend),
      grades = coalesce(array(select jsonb_array_elements_text(v_settings->'grades')), grades),
      fields = coalesce(array(select jsonb_array_elements_text(v_settings->'fields')), fields),
      logo_data = nullif(v_settings->>'logo_data',''),
      updated_by = auth.uid(), updated_at = now()
    where id = 1;
  end if;

  perform setval(pg_get_serial_sequence('public.members','id'), greatest(coalesce((select max(id) from public.members),1),1), true);
  perform setval(pg_get_serial_sequence('public.books','id'), greatest(coalesce((select max(id) from public.books),1),1), true);
  perform setval(pg_get_serial_sequence('public.loans','id'), greatest(coalesce((select max(id) from public.loans),1),1), true);

  perform public.write_audit('restore', 'backup', null, jsonb_build_object('members', v_members_count, 'books', v_books_count, 'loans', v_loans_count));
  return jsonb_build_object('ok', true, 'members', v_members_count, 'books', v_books_count, 'loans', v_loans_count);
end;
$$;

revoke execute on function public.current_user_role() from public, anon;
revoke execute on function public.is_active_user() from public, anon;
revoke execute on function public.is_admin() from public, anon;
revoke execute on function public.mark_login() from public, anon;
revoke execute on function public.issue_loan(bigint,bigint) from public, anon;
revoke execute on function public.return_loan(bigint) from public, anon;
revoke execute on function public.renew_loan(bigint) from public, anon;
revoke execute on function public.delete_loan(bigint) from public, anon;
revoke execute on function public.update_book_inventory(bigint,jsonb) from public, anon;
revoke execute on function public.restore_backup(jsonb) from public, anon;

revoke all on public.profiles, public.library_settings, public.members, public.books, public.loans, public.audit_logs from anon;
grant select, update on public.profiles to authenticated;
grant select, update on public.library_settings to authenticated;
grant select, insert, update, delete on public.members to authenticated;
grant select, insert, update, delete on public.books to authenticated;
grant select on public.loans to authenticated;
grant select on public.audit_logs to authenticated;
grant usage, select on all sequences in schema public to authenticated;

grant execute on function public.current_user_role() to authenticated;
grant execute on function public.is_active_user() to authenticated;
grant execute on function public.is_admin() to authenticated;
grant execute on function public.mark_login() to authenticated;
grant execute on function public.issue_loan(bigint,bigint) to authenticated;
grant execute on function public.return_loan(bigint) to authenticated;
grant execute on function public.renew_loan(bigint) to authenticated;
grant execute on function public.delete_loan(bigint) to authenticated;
grant execute on function public.update_book_inventory(bigint,jsonb) to authenticated;
grant execute on function public.restore_backup(jsonb) to authenticated;

commit;
